[colors]
ansi = [
  '#45475a', # surface1
  '#ef688e', # red
  '#8ada83', # green
  '#f6d488', # yellow
  '#649cf8', # blue
  '#ef9cd8', # pink
  '#77dac9', # teal
  '#bac2de', # subtext1
]
brights = [
  '#585b70', # surface2
  '#ef688e', # red
  '#8ada83', # green
  '#f6d488', # yellow
  '#649cf8', # blue
  '#ef9cd8', # pink
  '#77dac9', # teal
  '#a6adc8', # subtext0
]
compose_cursor = '#e9aaaa' # flamingo
cursor_bg = '#ebc0b8' # rosewater
cursor_border = '#ebc0b8' # rosewater
cursor_fg = '#11111b' # crust
foreground = '#cdd6f4' # text
background = '#000000' # '#0c0c13' # base #1e1e2e
scrollbar_thumb = '#585b70' # surface2
selection_bg = '#585b70' # surface2
selection_fg = '#cdd6f4' # text
split = '#6c7086' # overlay0
visual_bell = '#313244' # surface0

[colors.indexed]
16 = '#f89c62' # peach
17 = '#ebc0b8' # rosewater

[colors.tab_bar]
background = '#000000' # '#0c0c13' # base #1e1e2e
inactive_tab_edge = '#313244' # surface0

[colors.tab_bar.active_tab]
bg_color = '#b580f4' # mauve
fg_color = '#11111b' # crust
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#181825' # mantle
fg_color = '#cdd6f4' # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#000000' # '#0c0c13' # base #1e1e2e
fg_color = '#cdd6f4' # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#313244' # surface0
fg_color = '#cdd6f4' # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#45475a' # surface1
fg_color = '#cdd6f4' # text
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = ''
name = 'qwe'
